// flow-typed signature: fd82923d055ac2f4bb7acb12b5d483fa
// flow-typed version: <<STUB>>/animejs_v^2.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'animejs/anime' {
  declare module.exports: any;
}

declare module 'animejs/anime.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'animejs/anime.js' {
  declare module.exports: $Exports<'animejs/anime'>;
}
declare module 'animejs/anime.min.js' {
  declare module.exports: $Exports<'animejs/anime.min'>;
}
