// flow-typed signature: 57c4547ff882c5ef7930c0e7074c04de
// flow-typed version: <<STUB>>/ansi-html_v0.0.7/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansi-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansi-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ansi-html/index' {
  declare module.exports: $Exports<'ansi-html'>;
}
declare module 'ansi-html/index.js' {
  declare module.exports: $Exports<'ansi-html'>;
}
