// flow-typed signature: 554afcc2f936d8bafb530698048b514d
// flow-typed version: <<STUB>>/babel-helper-function-name_v^6.24.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-helper-function-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-helper-function-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-helper-function-name/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-helper-function-name/lib/index.js' {
  declare module.exports: $Exports<'babel-helper-function-name/lib/index'>;
}
