// flow-typed signature: 4a837f558a1d8790bf4a4c33ee63d2f6
// flow-typed version: <<STUB>>/babel-helpers_v^6.24.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-helpers/lib/helpers' {
  declare module.exports: any;
}

declare module 'babel-helpers/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-helpers/lib/helpers.js' {
  declare module.exports: $Exports<'babel-helpers/lib/helpers'>;
}
declare module 'babel-helpers/lib/index.js' {
  declare module.exports: $Exports<'babel-helpers/lib/index'>;
}
