// flow-typed signature: 47d2e971fe31aeb8e99df30e215d484a
// flow-typed version: <<STUB>>/babel-plugin-transform-do-expressions_v^6.22.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-do-expressions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-do-expressions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-do-expressions/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-do-expressions/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-do-expressions/lib/index'>;
}
