// flow-typed signature: 615d29321c3c3bf01ec54794460df2d1
// flow-typed version: <<STUB>>/builtin-status-codes_v^3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'builtin-status-codes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'builtin-status-codes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'builtin-status-codes/browser' {
  declare module.exports: any;
}

declare module 'builtin-status-codes/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'builtin-status-codes/browser.js' {
  declare module.exports: $Exports<'builtin-status-codes/browser'>;
}
declare module 'builtin-status-codes/build.js' {
  declare module.exports: $Exports<'builtin-status-codes/build'>;
}
declare module 'builtin-status-codes/index' {
  declare module.exports: $Exports<'builtin-status-codes'>;
}
declare module 'builtin-status-codes/index.js' {
  declare module.exports: $Exports<'builtin-status-codes'>;
}
