// flow-typed signature: 07d6d76678ae187108af9dc983d6d229
// flow-typed version: <<STUB>>/css-element-queries_v^0.4.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-element-queries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-element-queries' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-element-queries/src/ElementQueries' {
  declare module.exports: any;
}

declare module 'css-element-queries/src/ResizeSensor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-element-queries/index' {
  declare module.exports: $Exports<'css-element-queries'>;
}
declare module 'css-element-queries/index.js' {
  declare module.exports: $Exports<'css-element-queries'>;
}
declare module 'css-element-queries/src/ElementQueries.js' {
  declare module.exports: $Exports<'css-element-queries/src/ElementQueries'>;
}
declare module 'css-element-queries/src/ResizeSensor.js' {
  declare module.exports: $Exports<'css-element-queries/src/ResizeSensor'>;
}
