// flow-typed signature: 980be84dfa3e48982e7ae057991e2c2e
// flow-typed version: <<STUB>>/fs_v0.0.1-security/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs' {
  declare module.exports: any;
}
