// flow-typed signature: 9c4ec177dbdfc9db2e3fc1b05125787c
// flow-typed version: <<STUB>>/ieee754_v^1.1.8/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ieee754'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ieee754' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ieee754/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ieee754/index' {
  declare module.exports: $Exports<'ieee754'>;
}
declare module 'ieee754/index.js' {
  declare module.exports: $Exports<'ieee754'>;
}
declare module 'ieee754/test/basic.js' {
  declare module.exports: $Exports<'ieee754/test/basic'>;
}
