// flow-typed signature: 5382245a2004572716a06d8b71c0c604
// flow-typed version: <<STUB>>/jeet_v^7.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jeet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jeet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jeet/test/node-stylus/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jeet/index' {
  declare module.exports: $Exports<'jeet'>;
}
declare module 'jeet/index.js' {
  declare module.exports: $Exports<'jeet'>;
}
declare module 'jeet/test/node-stylus/node.js' {
  declare module.exports: $Exports<'jeet/test/node-stylus/node'>;
}
