// flow-typed signature: e96fd6ba56e15c327630d63a41d6786f
// flow-typed version: <<STUB>>/jest-serializer-vue_v^0.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-serializer-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-serializer-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-serializer-vue/build/gen-release-note' {
  declare module.exports: any;
}

declare module 'jest-serializer-vue/test/List.spec' {
  declare module.exports: any;
}

declare module 'jest-serializer-vue/test/ListSpaced.spec' {
  declare module.exports: any;
}

declare module 'jest-serializer-vue/test/Parent.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-serializer-vue/build/gen-release-note.js' {
  declare module.exports: $Exports<'jest-serializer-vue/build/gen-release-note'>;
}
declare module 'jest-serializer-vue/index' {
  declare module.exports: $Exports<'jest-serializer-vue'>;
}
declare module 'jest-serializer-vue/index.js' {
  declare module.exports: $Exports<'jest-serializer-vue'>;
}
declare module 'jest-serializer-vue/test/List.spec.js' {
  declare module.exports: $Exports<'jest-serializer-vue/test/List.spec'>;
}
declare module 'jest-serializer-vue/test/ListSpaced.spec.js' {
  declare module.exports: $Exports<'jest-serializer-vue/test/ListSpaced.spec'>;
}
declare module 'jest-serializer-vue/test/Parent.spec.js' {
  declare module.exports: $Exports<'jest-serializer-vue/test/Parent.spec'>;
}
