// flow-typed signature: 6cc1087a9ad5bb661c474755a85c2e16
// flow-typed version: <<STUB>>/postcss-property-lookup_v^1.2.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-property-lookup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-property-lookup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-property-lookup/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-property-lookup/build/index.js' {
  declare module.exports: $Exports<'postcss-property-lookup/build/index'>;
}
