// flow-typed signature: 7c3d0504efc6736bb5d3df08f8395e14
// flow-typed version: <<STUB>>/postcss-autoreset_v^2.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-autoreset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-autoreset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-autoreset/dist/createResetRule' {
  declare module.exports: any;
}

declare module 'postcss-autoreset/dist/index' {
  declare module.exports: any;
}

declare module 'postcss-autoreset/dist/resetRules' {
  declare module.exports: any;
}

declare module 'postcss-autoreset/dist/rulesInjectorFabric' {
  declare module.exports: any;
}

declare module 'postcss-autoreset/dist/rulesMatcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-autoreset/dist/createResetRule.js' {
  declare module.exports: $Exports<'postcss-autoreset/dist/createResetRule'>;
}
declare module 'postcss-autoreset/dist/index.js' {
  declare module.exports: $Exports<'postcss-autoreset/dist/index'>;
}
declare module 'postcss-autoreset/dist/resetRules.js' {
  declare module.exports: $Exports<'postcss-autoreset/dist/resetRules'>;
}
declare module 'postcss-autoreset/dist/rulesInjectorFabric.js' {
  declare module.exports: $Exports<'postcss-autoreset/dist/rulesInjectorFabric'>;
}
declare module 'postcss-autoreset/dist/rulesMatcher.js' {
  declare module.exports: $Exports<'postcss-autoreset/dist/rulesMatcher'>;
}
