// flow-typed signature: 5d486be1c07013ba71b0e72643781cab
// flow-typed version: <<STUB>>/postcss-grid-kiss_v^1.4.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-grid-kiss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-grid-kiss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-grid-kiss/dist/align-content' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/align-self' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/calc-utils' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/dimension' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/fallback' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/grid-template-areas' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/grid-template-columns' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/grid-template-rows' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/index' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/justify-content' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/justify-self' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/main' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/parse' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/dist/utils' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/align-content' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/align-self' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/calc-utils' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/dimension' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/fallback' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/grid-template-areas' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/grid-template-columns' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/grid-template-rows' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/index' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/justify-content' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/justify-self' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/main' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/parse' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/src/utils' {
  declare module.exports: any;
}

declare module 'postcss-grid-kiss/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-grid-kiss/dist/align-content.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/align-content'>;
}
declare module 'postcss-grid-kiss/dist/align-self.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/align-self'>;
}
declare module 'postcss-grid-kiss/dist/calc-utils.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/calc-utils'>;
}
declare module 'postcss-grid-kiss/dist/dimension.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/dimension'>;
}
declare module 'postcss-grid-kiss/dist/fallback.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/fallback'>;
}
declare module 'postcss-grid-kiss/dist/grid-template-areas.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/grid-template-areas'>;
}
declare module 'postcss-grid-kiss/dist/grid-template-columns.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/grid-template-columns'>;
}
declare module 'postcss-grid-kiss/dist/grid-template-rows.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/grid-template-rows'>;
}
declare module 'postcss-grid-kiss/dist/index.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/index'>;
}
declare module 'postcss-grid-kiss/dist/justify-content.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/justify-content'>;
}
declare module 'postcss-grid-kiss/dist/justify-self.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/justify-self'>;
}
declare module 'postcss-grid-kiss/dist/main.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/main'>;
}
declare module 'postcss-grid-kiss/dist/parse.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/parse'>;
}
declare module 'postcss-grid-kiss/dist/utils.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/dist/utils'>;
}
declare module 'postcss-grid-kiss/src/align-content.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/align-content'>;
}
declare module 'postcss-grid-kiss/src/align-self.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/align-self'>;
}
declare module 'postcss-grid-kiss/src/calc-utils.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/calc-utils'>;
}
declare module 'postcss-grid-kiss/src/dimension.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/dimension'>;
}
declare module 'postcss-grid-kiss/src/fallback.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/fallback'>;
}
declare module 'postcss-grid-kiss/src/grid-template-areas.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/grid-template-areas'>;
}
declare module 'postcss-grid-kiss/src/grid-template-columns.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/grid-template-columns'>;
}
declare module 'postcss-grid-kiss/src/grid-template-rows.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/grid-template-rows'>;
}
declare module 'postcss-grid-kiss/src/index.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/index'>;
}
declare module 'postcss-grid-kiss/src/justify-content.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/justify-content'>;
}
declare module 'postcss-grid-kiss/src/justify-self.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/justify-self'>;
}
declare module 'postcss-grid-kiss/src/main.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/main'>;
}
declare module 'postcss-grid-kiss/src/parse.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/parse'>;
}
declare module 'postcss-grid-kiss/src/utils.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/src/utils'>;
}
declare module 'postcss-grid-kiss/test.js' {
  declare module.exports: $Exports<'postcss-grid-kiss/test'>;
}
