// flow-typed signature: 478c836a36a98a32609118468f79a4c5
// flow-typed version: <<STUB>>/postcss-initial_v^2.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-initial'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-initial' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-initial/lib/rules-fabric' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-initial/index' {
  declare module.exports: $Exports<'postcss-initial'>;
}
declare module 'postcss-initial/index.js' {
  declare module.exports: $Exports<'postcss-initial'>;
}
declare module 'postcss-initial/lib/rules-fabric.js' {
  declare module.exports: $Exports<'postcss-initial/lib/rules-fabric'>;
}
