// flow-typed signature: 0e8a2de2da8dac25fdbaa0e23a24ebfe
// flow-typed version: <<STUB>>/postcss-animation_v0.0.12/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-animation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-animation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-animation/gulpfile' {
  declare module.exports: any;
}

declare module 'postcss-animation/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-animation/gulpfile.js' {
  declare module.exports: $Exports<'postcss-animation/gulpfile'>;
}
declare module 'postcss-animation/index' {
  declare module.exports: $Exports<'postcss-animation'>;
}
declare module 'postcss-animation/index.js' {
  declare module.exports: $Exports<'postcss-animation'>;
}
declare module 'postcss-animation/test/test.js' {
  declare module.exports: $Exports<'postcss-animation/test/test'>;
}
