// flow-typed signature: c2ceeaffdec219c8b0504923d3937680
// flow-typed version: <<STUB>>/postcss-opacity_v^4.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-opacity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-opacity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-opacity/index' {
  declare module.exports: $Exports<'postcss-opacity'>;
}
declare module 'postcss-opacity/index.js' {
  declare module.exports: $Exports<'postcss-opacity'>;
}
