// flow-typed signature: f1ba7fd9aa3c9d9b29b9ab119626edd2
// flow-typed version: <<STUB>>/postcss-color-rgba-fallback_v^2.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-color-rgba-fallback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-color-rgba-fallback' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-color-rgba-fallback/index' {
  declare module.exports: $Exports<'postcss-color-rgba-fallback'>;
}
declare module 'postcss-color-rgba-fallback/index.js' {
  declare module.exports: $Exports<'postcss-color-rgba-fallback'>;
}
