// flow-typed signature: 187818bf448cf4737b1e67f5a59472ae
// flow-typed version: <<STUB>>/postcss-vmin_v^3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-vmin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-vmin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-vmin/index' {
  declare module.exports: $Exports<'postcss-vmin'>;
}
declare module 'postcss-vmin/index.js' {
  declare module.exports: $Exports<'postcss-vmin'>;
}
