// flow-typed signature: c9c7bd8f526e0458210c88c95e8097c9
// flow-typed version: <<STUB>>/postcss-transform-shortcut_v^2.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-transform-shortcut'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-transform-shortcut' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-transform-shortcut/index' {
  declare module.exports: $Exports<'postcss-transform-shortcut'>;
}
declare module 'postcss-transform-shortcut/index.js' {
  declare module.exports: $Exports<'postcss-transform-shortcut'>;
}
