// flow-typed signature: a5513ad27dbc750da2fe8a1ad5132a95
// flow-typed version: <<STUB>>/purify-css_v^1.2.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'purify-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'purify-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'purify-css/__tests__/index' {
  declare module.exports: any;
}

declare module 'purify-css/__tests__/test_examples/camel_case/camel_case' {
  declare module.exports: any;
}

declare module 'purify-css/__tests__/test_examples/combined/combined' {
  declare module.exports: any;
}

declare module 'purify-css/__tests__/test_examples/multiple_files/multiple_files' {
  declare module.exports: any;
}

declare module 'purify-css/__tests__/test_examples/pseudo_class/pseudo_class' {
  declare module.exports: any;
}

declare module 'purify-css/__tests__/test_examples/remove_unused/remove_unused' {
  declare module.exports: any;
}

declare module 'purify-css/__tests__/test_examples/simple/simple' {
  declare module.exports: any;
}

declare module 'purify-css/__tests__/test_examples/special_characters/special_characters' {
  declare module.exports: any;
}

declare module 'purify-css/config/rollup.config' {
  declare module.exports: any;
}

declare module 'purify-css/lib/purifycss.es' {
  declare module.exports: any;
}

declare module 'purify-css/lib/purifycss' {
  declare module.exports: any;
}

declare module 'purify-css/src/CssTreeWalker' {
  declare module.exports: any;
}

declare module 'purify-css/src/purifycss' {
  declare module.exports: any;
}

declare module 'purify-css/src/SelectorFilter' {
  declare module.exports: any;
}

declare module 'purify-css/src/utils/ExtractWordsUtil' {
  declare module.exports: any;
}

declare module 'purify-css/src/utils/FileUtil' {
  declare module.exports: any;
}

declare module 'purify-css/src/utils/PrintUtil' {
  declare module.exports: any;
}

// Filename aliases
declare module 'purify-css/__tests__/index.js' {
  declare module.exports: $Exports<'purify-css/__tests__/index'>;
}
declare module 'purify-css/__tests__/test_examples/camel_case/camel_case.js' {
  declare module.exports: $Exports<'purify-css/__tests__/test_examples/camel_case/camel_case'>;
}
declare module 'purify-css/__tests__/test_examples/combined/combined.js' {
  declare module.exports: $Exports<'purify-css/__tests__/test_examples/combined/combined'>;
}
declare module 'purify-css/__tests__/test_examples/multiple_files/multiple_files.js' {
  declare module.exports: $Exports<'purify-css/__tests__/test_examples/multiple_files/multiple_files'>;
}
declare module 'purify-css/__tests__/test_examples/pseudo_class/pseudo_class.js' {
  declare module.exports: $Exports<'purify-css/__tests__/test_examples/pseudo_class/pseudo_class'>;
}
declare module 'purify-css/__tests__/test_examples/remove_unused/remove_unused.js' {
  declare module.exports: $Exports<'purify-css/__tests__/test_examples/remove_unused/remove_unused'>;
}
declare module 'purify-css/__tests__/test_examples/simple/simple.js' {
  declare module.exports: $Exports<'purify-css/__tests__/test_examples/simple/simple'>;
}
declare module 'purify-css/__tests__/test_examples/special_characters/special_characters.js' {
  declare module.exports: $Exports<'purify-css/__tests__/test_examples/special_characters/special_characters'>;
}
declare module 'purify-css/config/rollup.config.js' {
  declare module.exports: $Exports<'purify-css/config/rollup.config'>;
}
declare module 'purify-css/lib/purifycss.es.js' {
  declare module.exports: $Exports<'purify-css/lib/purifycss.es'>;
}
declare module 'purify-css/lib/purifycss.js' {
  declare module.exports: $Exports<'purify-css/lib/purifycss'>;
}
declare module 'purify-css/src/CssTreeWalker.js' {
  declare module.exports: $Exports<'purify-css/src/CssTreeWalker'>;
}
declare module 'purify-css/src/purifycss.js' {
  declare module.exports: $Exports<'purify-css/src/purifycss'>;
}
declare module 'purify-css/src/SelectorFilter.js' {
  declare module.exports: $Exports<'purify-css/src/SelectorFilter'>;
}
declare module 'purify-css/src/utils/ExtractWordsUtil.js' {
  declare module.exports: $Exports<'purify-css/src/utils/ExtractWordsUtil'>;
}
declare module 'purify-css/src/utils/FileUtil.js' {
  declare module.exports: $Exports<'purify-css/src/utils/FileUtil'>;
}
declare module 'purify-css/src/utils/PrintUtil.js' {
  declare module.exports: $Exports<'purify-css/src/utils/PrintUtil'>;
}
