// flow-typed signature: 67871c38a9bca99a9549e8366b9402dd
// flow-typed version: <<STUB>>/quasar-framework_v^0.14.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'quasar-framework'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'quasar-framework' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'quasar-framework/dist/quasar.esm' {
  declare module.exports: any;
}

declare module 'quasar-framework/dist/quasar.ie' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/components/action-sheet/action-sheet' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/components/dialog/dialog' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/components/loading/loading' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/components/modal-generator' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/components/toast/toast' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/addressbar-color' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/app-fullscreen' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/app-visibility' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/body-classes' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/cookies' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/error-handler' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/escape-key' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/events' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/fastclick' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/platform' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/polyfills' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/theme' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/features/web-storage' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/index.es6' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/index' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/standalone-install' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/start' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/animate' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/clone' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/colors' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/debounce' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/dom' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/event' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/extend' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/filter' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/format' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/open-url' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/popup' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/scrollbar' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/store' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/throttle' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/utils/uid' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/data-table/plugins/column-selection/column-selection' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/data-table/plugins/filter/filter' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/data-table/plugins/i18n/i18n' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/data-table/plugins/pagination/pagination' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/data-table/plugins/responsive/responsive' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/data-table/plugins/row-selection/row-selection' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/data-table/plugins/scroll/scroll' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/data-table/plugins/sort/sort' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/data-table/plugins/sticky-cols/sticky-cols' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/datetime/datetime-props' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-components/slider/slider-mixin' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-directives/back-to-top' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-directives/go-back' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-directives/link' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-directives/scroll-fire' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-directives/scroll' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-directives/touch-hold' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-directives/touch-pan' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-directives/touch-swipe' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-install' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-transitions/index' {
  declare module.exports: any;
}

declare module 'quasar-framework/src/vue-transitions/slide-toggle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'quasar-framework/dist/quasar.esm.js' {
  declare module.exports: $Exports<'quasar-framework/dist/quasar.esm'>;
}
declare module 'quasar-framework/dist/quasar.ie.js' {
  declare module.exports: $Exports<'quasar-framework/dist/quasar.ie'>;
}
declare module 'quasar-framework/src/components/action-sheet/action-sheet.js' {
  declare module.exports: $Exports<'quasar-framework/src/components/action-sheet/action-sheet'>;
}
declare module 'quasar-framework/src/components/dialog/dialog.js' {
  declare module.exports: $Exports<'quasar-framework/src/components/dialog/dialog'>;
}
declare module 'quasar-framework/src/components/loading/loading.js' {
  declare module.exports: $Exports<'quasar-framework/src/components/loading/loading'>;
}
declare module 'quasar-framework/src/components/modal-generator.js' {
  declare module.exports: $Exports<'quasar-framework/src/components/modal-generator'>;
}
declare module 'quasar-framework/src/components/toast/toast.js' {
  declare module.exports: $Exports<'quasar-framework/src/components/toast/toast'>;
}
declare module 'quasar-framework/src/features/addressbar-color.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/addressbar-color'>;
}
declare module 'quasar-framework/src/features/app-fullscreen.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/app-fullscreen'>;
}
declare module 'quasar-framework/src/features/app-visibility.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/app-visibility'>;
}
declare module 'quasar-framework/src/features/body-classes.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/body-classes'>;
}
declare module 'quasar-framework/src/features/cookies.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/cookies'>;
}
declare module 'quasar-framework/src/features/error-handler.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/error-handler'>;
}
declare module 'quasar-framework/src/features/escape-key.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/escape-key'>;
}
declare module 'quasar-framework/src/features/events.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/events'>;
}
declare module 'quasar-framework/src/features/fastclick.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/fastclick'>;
}
declare module 'quasar-framework/src/features/platform.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/platform'>;
}
declare module 'quasar-framework/src/features/polyfills.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/polyfills'>;
}
declare module 'quasar-framework/src/features/theme.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/theme'>;
}
declare module 'quasar-framework/src/features/web-storage.js' {
  declare module.exports: $Exports<'quasar-framework/src/features/web-storage'>;
}
declare module 'quasar-framework/src/index.es6.js' {
  declare module.exports: $Exports<'quasar-framework/src/index.es6'>;
}
declare module 'quasar-framework/src/index.js' {
  declare module.exports: $Exports<'quasar-framework/src/index'>;
}
declare module 'quasar-framework/src/standalone-install.js' {
  declare module.exports: $Exports<'quasar-framework/src/standalone-install'>;
}
declare module 'quasar-framework/src/start.js' {
  declare module.exports: $Exports<'quasar-framework/src/start'>;
}
declare module 'quasar-framework/src/utils.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils'>;
}
declare module 'quasar-framework/src/utils/animate.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/animate'>;
}
declare module 'quasar-framework/src/utils/clone.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/clone'>;
}
declare module 'quasar-framework/src/utils/colors.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/colors'>;
}
declare module 'quasar-framework/src/utils/debounce.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/debounce'>;
}
declare module 'quasar-framework/src/utils/dom.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/dom'>;
}
declare module 'quasar-framework/src/utils/event.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/event'>;
}
declare module 'quasar-framework/src/utils/extend.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/extend'>;
}
declare module 'quasar-framework/src/utils/filter.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/filter'>;
}
declare module 'quasar-framework/src/utils/format.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/format'>;
}
declare module 'quasar-framework/src/utils/open-url.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/open-url'>;
}
declare module 'quasar-framework/src/utils/popup.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/popup'>;
}
declare module 'quasar-framework/src/utils/scrollbar.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/scrollbar'>;
}
declare module 'quasar-framework/src/utils/store.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/store'>;
}
declare module 'quasar-framework/src/utils/throttle.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/throttle'>;
}
declare module 'quasar-framework/src/utils/uid.js' {
  declare module.exports: $Exports<'quasar-framework/src/utils/uid'>;
}
declare module 'quasar-framework/src/vue-components/data-table/plugins/column-selection/column-selection.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/data-table/plugins/column-selection/column-selection'>;
}
declare module 'quasar-framework/src/vue-components/data-table/plugins/filter/filter.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/data-table/plugins/filter/filter'>;
}
declare module 'quasar-framework/src/vue-components/data-table/plugins/i18n/i18n.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/data-table/plugins/i18n/i18n'>;
}
declare module 'quasar-framework/src/vue-components/data-table/plugins/pagination/pagination.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/data-table/plugins/pagination/pagination'>;
}
declare module 'quasar-framework/src/vue-components/data-table/plugins/responsive/responsive.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/data-table/plugins/responsive/responsive'>;
}
declare module 'quasar-framework/src/vue-components/data-table/plugins/row-selection/row-selection.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/data-table/plugins/row-selection/row-selection'>;
}
declare module 'quasar-framework/src/vue-components/data-table/plugins/scroll/scroll.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/data-table/plugins/scroll/scroll'>;
}
declare module 'quasar-framework/src/vue-components/data-table/plugins/sort/sort.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/data-table/plugins/sort/sort'>;
}
declare module 'quasar-framework/src/vue-components/data-table/plugins/sticky-cols/sticky-cols.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/data-table/plugins/sticky-cols/sticky-cols'>;
}
declare module 'quasar-framework/src/vue-components/datetime/datetime-props.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/datetime/datetime-props'>;
}
declare module 'quasar-framework/src/vue-components/slider/slider-mixin.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-components/slider/slider-mixin'>;
}
declare module 'quasar-framework/src/vue-directives/back-to-top.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-directives/back-to-top'>;
}
declare module 'quasar-framework/src/vue-directives/go-back.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-directives/go-back'>;
}
declare module 'quasar-framework/src/vue-directives/link.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-directives/link'>;
}
declare module 'quasar-framework/src/vue-directives/scroll-fire.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-directives/scroll-fire'>;
}
declare module 'quasar-framework/src/vue-directives/scroll.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-directives/scroll'>;
}
declare module 'quasar-framework/src/vue-directives/touch-hold.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-directives/touch-hold'>;
}
declare module 'quasar-framework/src/vue-directives/touch-pan.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-directives/touch-pan'>;
}
declare module 'quasar-framework/src/vue-directives/touch-swipe.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-directives/touch-swipe'>;
}
declare module 'quasar-framework/src/vue-install.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-install'>;
}
declare module 'quasar-framework/src/vue-transitions/index.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-transitions/index'>;
}
declare module 'quasar-framework/src/vue-transitions/slide-toggle.js' {
  declare module.exports: $Exports<'quasar-framework/src/vue-transitions/slide-toggle'>;
}
