// flow-typed signature: b8d279863f018bd69057cc2a4f4d84aa
// flow-typed version: <<STUB>>/roboto-fontface_v^0.7.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'roboto-fontface'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'roboto-fontface' {
  declare module.exports: any;
}
