// flow-typed signature: 33d738e8fd8c68326378d720bd9a5272
// flow-typed version: <<STUB>>/suitcss-utils-position_v^1.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-utils-position'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-utils-position' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'suitcss-utils-position/index' {
  declare module.exports: $Exports<'suitcss-utils-position'>;
}
declare module 'suitcss-utils-position/index.js' {
  declare module.exports: $Exports<'suitcss-utils-position'>;
}
