// flow-typed signature: 4f0d9a4b3f11c62a4e1398c7cefc44c9
// flow-typed version: <<STUB>>/suitcss_v^3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss' {
  declare module.exports: any;
}
