// flow-typed signature: 50ccc6c6f1e9b980c6b735e3e2fb66f3
// flow-typed version: <<STUB>>/suitcss-utils-text_v^1.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-utils-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-utils-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'suitcss-utils-text/index' {
  declare module.exports: $Exports<'suitcss-utils-text'>;
}
declare module 'suitcss-utils-text/index.js' {
  declare module.exports: $Exports<'suitcss-utils-text'>;
}
