// flow-typed signature: 2ff6cd6a2c8b371ab6b4aa0cd4e67757
// flow-typed version: <<STUB>>/suitcss-utils_v^3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'suitcss-utils/index' {
  declare module.exports: $Exports<'suitcss-utils'>;
}
declare module 'suitcss-utils/index.js' {
  declare module.exports: $Exports<'suitcss-utils'>;
}
