// flow-typed signature: 20ac980d2e956fd8efc44dcb21f4a52b
// flow-typed version: <<STUB>>/suitcss-base_v^3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'suitcss-base/index' {
  declare module.exports: $Exports<'suitcss-base'>;
}
declare module 'suitcss-base/index.js' {
  declare module.exports: $Exports<'suitcss-base'>;
}
