// flow-typed signature: ea1688d2fe46cf1722d50d4a98c9adbf
// flow-typed version: <<STUB>>/to-arraybuffer_v^1.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-arraybuffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-arraybuffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-arraybuffer/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-arraybuffer/index' {
  declare module.exports: $Exports<'to-arraybuffer'>;
}
declare module 'to-arraybuffer/index.js' {
  declare module.exports: $Exports<'to-arraybuffer'>;
}
declare module 'to-arraybuffer/test.js' {
  declare module.exports: $Exports<'to-arraybuffer/test'>;
}
