// flow-typed signature: f63a97122035dbc9fb6a9bfa1b0a108a
// flow-typed version: <<STUB>>/vue-style-loader_v^3.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-style-loader/lib/addStylesClient' {
  declare module.exports: any;
}

declare module 'vue-style-loader/lib/addStylesServer' {
  declare module.exports: any;
}

declare module 'vue-style-loader/lib/listToStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-style-loader/index' {
  declare module.exports: $Exports<'vue-style-loader'>;
}
declare module 'vue-style-loader/index.js' {
  declare module.exports: $Exports<'vue-style-loader'>;
}
declare module 'vue-style-loader/lib/addStylesClient.js' {
  declare module.exports: $Exports<'vue-style-loader/lib/addStylesClient'>;
}
declare module 'vue-style-loader/lib/addStylesServer.js' {
  declare module.exports: $Exports<'vue-style-loader/lib/addStylesServer'>;
}
declare module 'vue-style-loader/lib/listToStyles.js' {
  declare module.exports: $Exports<'vue-style-loader/lib/listToStyles'>;
}
