// flow-typed signature: c3aa12b3bb4e818dffe666bd559b7e67
// flow-typed version: <<STUB>>/vuex_v^2.3.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuex/dist/logger' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.common' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.esm' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuex/dist/logger.js' {
  declare module.exports: $Exports<'vuex/dist/logger'>;
}
declare module 'vuex/dist/vuex.common.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.common'>;
}
declare module 'vuex/dist/vuex.esm.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.esm'>;
}
declare module 'vuex/dist/vuex.js' {
  declare module.exports: $Exports<'vuex/dist/vuex'>;
}
declare module 'vuex/dist/vuex.min.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.min'>;
}
