// flow-typed signature: 89a0c338888ab853e5703e9ab399f81e
// flow-typed version: <<STUB>>/webpack-babel-jest_v^1.0.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-babel-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-babel-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-babel-jest/index' {
  declare module.exports: $Exports<'webpack-babel-jest'>;
}
declare module 'webpack-babel-jest/index.js' {
  declare module.exports: $Exports<'webpack-babel-jest'>;
}
